Flying Around/force-app/main/default/objects/Airport__c/Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Flying Around/force-app/main/default/objects/Airport__c/fields/IATA__c.field-meta.xml
<CustomField>
    <fullName>IATA__c</fullName>
    <label>IATA</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Flying Around/force-app/main/default/classes/TestDataFactory.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-22-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class TestDataFactory {

    public static Airport__c createAirport(String name, String iataCode, Decimal latitude, Decimal longitude) {

        Airport__c newAirport = new Airport__c();
        newAirport.Name = name;
        newAirport.IATA__c = iataCode;
        newAirport.Geolocation__Latitude__s = latitude;
        newAirport.Geolocation__Longitude__s = longitude;

        insert newAirport;
        
        return newAirport;

    }
}